name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        
    - name: Install dependencies
      run: |
        uv venv
        . .venv/bin/activate
        uv pip install -r requirements.txt
        
    - name: Run ruff linting
      run: |
        . .venv/bin/activate
        ruff check .

    - name: Check ruff formatting
      run: |
        . .venv/bin/activate
        ruff format --check .
      
    - name: Run pyright
      run: |
        . .venv/bin/activate
        pyright